### PR TITLE
Add dark theme (Followup to #2)

### PR DESCRIPTION
**Pull request by VFDan**
This is a followup to #2, and I added the code.

**However, this only works on the homepage and project pages.**

### CODE REVIEW

**Comment by MasterOfTheTiger** [comment]
Awesome! I do believe that more work will have to be done to make it apply on other pages as well. In addition, I will add an option to change themes in the next version.

**Comment by moeenio** [comment]
How do I turn the dark mode on ? @MasterOfTheTiger

**Comment by MasterOfTheTiger** [comment]
Not implemented yet. I apologize

**Comment by moeenio** [comment]
That's fine.

**Pull request merged**
